# Generated by Django 5.2.8 on 2025-11-26 18:49

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DisclosureReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('source_url', models.URLField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('organization_name', models.CharField(blank=True, db_index=True, max_length=500)),
                ('organization_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('report_type', models.CharField(blank=True, max_length=200)),
                ('begin_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('submit_date', models.DateField(blank=True, null=True)),
                ('balance_beginning', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_contributions', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_expenditures', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('ending_balance', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('report_info', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='disclosures_created_1ff40f_idx'), models.Index(fields=['report_id'], name='disclosures_report__0d695a_idx'), models.Index(fields=['organization_type'], name='disclosures_organiz_f9a30b_idx'), models.Index(fields=['organization_name'], name='disclosures_organiz_c5f997_idx')],
            },
        ),
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField(blank=True, null=True)),
                ('date_received_raw', models.CharField(blank=True, max_length=50)),
                ('contributor_name', models.CharField(max_length=500)),
                ('address', models.TextField(blank=True)),
                ('is_in_kind', models.BooleanField(default=False)),
                ('is_loan', models.BooleanField(default=False)),
                ('is_amendment', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='disclosures.disclosurereport')),
            ],
            options={
                'ordering': ['-date_received', '-created_at'],
                'indexes': [models.Index(fields=['report', '-date_received'], name='disclosures_report__08f385_idx'), models.Index(fields=['contributor_name'], name='disclosures_contrib_0c9f4a_idx'), models.Index(fields=['-amount'], name='disclosures_amount_c4ff7e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('date_raw', models.CharField(blank=True, max_length=50)),
                ('recipient_name', models.CharField(max_length=500)),
                ('purpose', models.TextField(blank=True)),
                ('is_in_kind', models.BooleanField(default=False)),
                ('is_loan', models.BooleanField(default=False)),
                ('is_amendment', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='disclosures.disclosurereport')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['report', '-date'], name='disclosures_report__0f815b_idx'), models.Index(fields=['recipient_name'], name='disclosures_recipie_fae952_idx'), models.Index(fields=['-amount'], name='disclosures_amount_c53a40_idx')],
            },
        ),
    ]
