# Generated by Django 5.2.8 on 2025-11-28 01:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disclosures', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('source_url', models.URLField(max_length=500)),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('also_known_as', models.CharField(blank=True, max_length=500)),
                ('entity_type', models.CharField(blank=True, max_length=100)),
                ('date_created', models.DateField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=50)),
                ('street_address', models.CharField(blank=True, max_length=500)),
                ('suite_po_box', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_id'], name='disclosures_entity__806510_idx'), models.Index(fields=['name'], name='disclosures_name_0c09dc_idx')],
            },
        ),
        migrations.CreateModel(
            name='EntityOfficer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=200)),
                ('occupation', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('street_address', models.CharField(blank=True, max_length=500)),
                ('suite_po_box', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('order', models.IntegerField(default=0)),
                ('is_treasurer', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='officers', to='disclosures.entityregistration')),
            ],
            options={
                'ordering': ['entity', 'order'],
            },
        ),
    ]
