# Generated by Django 5.2.8 on 2025-11-29 17:51

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disclosures', '0002_entityregistration_entityofficer'),
    ]

    operations = [
        migrations.CreateModel(
            name='LobbyistRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('source_url', models.URLField(max_length=500)),
                ('first_name', models.CharField(blank=True, max_length=200)),
                ('last_name', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(db_index=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('registration_date', models.DateField(blank=True, null=True)),
                ('organization_name', models.CharField(blank=True, max_length=500)),
                ('organization_phone', models.CharField(blank=True, max_length=50)),
                ('street_address', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(blank=True, max_length=200)),
                ('state', models.CharField(blank=True, max_length=2)),
                ('zip_code', models.CharField(blank=True, max_length=10)),
                ('principal_name', models.CharField(blank=True, max_length=500)),
                ('principal_phone', models.CharField(blank=True, max_length=50)),
                ('principal_address', models.TextField(blank=True)),
                ('lobbying_purposes', models.TextField(blank=True)),
                ('raw_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_id'], name='disclosures_entity__202579_idx'), models.Index(fields=['name'], name='disclosures_name_cdfe55_idx'), models.Index(fields=['organization_name'], name='disclosures_organiz_a28220_idx')],
            },
        ),
        migrations.CreateModel(
            name='LobbyistPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('contact', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lobbyist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principals', to='disclosures.lobbyistregistration')),
            ],
            options={
                'ordering': ['lobbyist', 'order'],
            },
        ),
        migrations.CreateModel(
            name='LobbyistReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(db_index=True, max_length=50, unique=True)),
                ('source_url', models.URLField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=500)),
                ('principal_name', models.CharField(blank=True, db_index=True, max_length=500)),
                ('principal_phone', models.CharField(blank=True, max_length=50)),
                ('principal_street_address', models.CharField(blank=True, max_length=500)),
                ('principal_city', models.CharField(blank=True, max_length=200)),
                ('principal_state', models.CharField(blank=True, max_length=2)),
                ('principal_zip', models.CharField(blank=True, max_length=10)),
                ('report_type', models.CharField(blank=True, max_length=200)),
                ('begin_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('submit_date', models.DateField(blank=True, null=True)),
                ('total_expenditures', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('report_info', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_scraped_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='disclosures_created_eb7a08_idx'), models.Index(fields=['report_id'], name='disclosures_report__10a5f6_idx'), models.Index(fields=['principal_name'], name='disclosures_princip_3b2692_idx')],
            },
        ),
        migrations.CreateModel(
            name='LobbyistExpenditure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('date_raw', models.CharField(blank=True, max_length=50)),
                ('recipient_name', models.CharField(db_index=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=500)),
                ('purpose', models.TextField(blank=True)),
                ('is_amendment', models.BooleanField(default=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenditures', to='disclosures.lobbyistreport')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['report', '-date'], name='disclosures_report__c613ca_idx'), models.Index(fields=['recipient_name'], name='disclosures_recipie_8a458e_idx'), models.Index(fields=['-amount'], name='disclosures_amount_4af08a_idx')],
            },
        ),
    ]
