# Generated by Django 5.2.8 on 2025-12-02 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disclosures', '0004_performance_indexes'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='contribution',
            name='contrib_name_amt_idx',
        ),
        migrations.RemoveIndex(
            model_name='contribution',
            name='contrib_addr_amt_idx',
        ),
        migrations.RemoveIndex(
            model_name='contribution',
            name='contrib_date_amt_idx',
        ),
        migrations.RemoveIndex(
            model_name='disclosurereport',
            name='report_end_orgtype_idx',
        ),
        migrations.RemoveIndex(
            model_name='expenditure',
            name='exp_recip_amt_idx',
        ),
        migrations.RemoveIndex(
            model_name='expenditure',
            name='exp_date_amt_idx',
        ),
        migrations.AddField(
            model_name='expenditure',
            name='address',
            field=models.TextField(blank=True),
        ),
    ]
